### ISSUE TITLE
Iniciar diagnóstico - ERRO

### ISSUE THREAD

**Issue by Bdelmedico** [janssenlima/ZabbixTuner#12]
--- Escolha uma opção do menu ---

[1] - Relatório de itens do sistema
[2] - Listar itens não suportados
[3] - Desabilitar itens não suportados
[4] - Relatório da média de coleta dos itens (por tipo)
[5] - Iniciar diagnóstico
[6] - Relatório de Agentes Zabbix desatualizados
[7] - Relatório de Triggers por tempo de alarme e estado

[0] - Sair

[+] - Selecione uma opção[0-7]: 5
[+++] analisando itens não númericos
[+++] analisando itens ICMPPING com histórico acima de 7 dias
Traceback (most recent call last):
  File "./ZabbixTuner.py", line 486, in <module>
    main()
  File "./ZabbixTuner.py", line 484, in main
    menu()
  File "./ZabbixTuner.py", line 59, in menu
    menu_opcao()
  File "./ZabbixTuner.py", line 74, in menu_opcao
    menu_relack()
  File "./ZabbixTuner.py", line 409, in menu_relack
    menu_opcao_relack()
  File "./ZabbixTuner.py", line 446, in menu_opcao_relack
    menu_relack()
  File "./ZabbixTuner.py", line 409, in menu_relack
    menu_opcao_relack()
  File "./ZabbixTuner.py", line 481, in menu_opcao_relack
    menu_relack()
  File "./ZabbixTuner.py", line 409, in menu_relack
    menu_opcao_relack()
  File "./ZabbixTuner.py", line 425, in menu_opcao_relack
    main()
  File "./ZabbixTuner.py", line 484, in main
    menu()
  File "./ZabbixTuner.py", line 59, in menu
    menu_opcao()
  File "./ZabbixTuner.py", line 70, in menu_opcao
    diagnosticoAmbiente()
  File "./ZabbixTuner.py", line 164, in diagnosticoAmbiente
    if int(x["history"]) > 7:
ValueError: invalid literal for int() with base 10: '365d'

**Comment by jeffersondsilveira** [comment]
Estou com o mesmo problema na versão 4.0.5.

**Comment by janssenlima** [comment]
Já coloquei na fila para corrigir esse problema.

**Comment by Filipe-Mariano** [comment]
Mesmo erro.
![Capturar](https://user-images.githubusercontent.com/11853709/56079474-64a83400-5dcb-11e9-8ad6-264437306c83.PNG)

**Comment by janssenlima** [comment]
Fixed.
