### ISSUE TITLE
Erro na criação de relatórios usando python 3

### ISSUE THREAD

**Issue by petersonbasso** [janssenlima/ZabbixTuner#19]
Ao tentar selecionar a opção de criação de relatório usando python 3, ocorre o erro abaixo.
```
Deseja gerar relatorio em arquivo? [s/n]s
Traceback (most recent call last):
  File "./ZabbixTuner.py", line 428, in <module>
    main()
  File "./ZabbixTuner.py", line 425, in main
    menu()
  File "./ZabbixTuner.py", line 58, in menu
    menu_opcao()
  File "./ZabbixTuner.py", line 65, in menu_opcao
    listagemItensNaoSuportados()
  File "./ZabbixTuner.py", line 199, in listagemItensNaoSuportados
    arquivo.write(("\"" + relatorio["name"].replace('"', '') + "\"").encode('utf-8'))
TypeError: write() argument must be str, not bytes
```
Aparentemente esse erro é devido no python 3 o método `.encode()` retornar um conjunto de bytes e não uma string, necessária como argumento do método `write`

**Comment by joel-vasiliev** [comment]
I am having the same issue, how do you solved it?

**Comment by joelvasiliev** [comment]
estou tendo o mesmo problema, como vc resolveu?
