### ISSUE TITLE
Erro de timeout ao executar a opção 1 do menu

### ISSUE THREAD

**Issue by janssenlima** [janssenlima/ZabbixTuner#5]
Isto se deve ao fato das operações na base de dados do Zabbix. O servidor demora para responder as requisições e a API retorna erro de timeout.

Ajustar as requisições da função de itens.
Talvez separar as requisições e retornar os valores para função principal resolva o problema.

Verificar.

**Comment by tiago-cruz-movile** [comment]
Mesma coisa aqui :)

```
[+] - Selecione uma opção[0-9]: 1
Traceback (most recent call last):
  File "./ZabbixTuner.py", line 361, in <module>
    main()
  File "./ZabbixTuner.py", line 359, in main
    menu()
  File "./ZabbixTuner.py", line 53, in menu
    menu_opcao()
  File "./ZabbixTuner.py", line 58, in menu_opcao
    dadosItens()
  File "./ZabbixTuner.py", line 186, in dadosItens
    "monitored": True
  File "/usr/local/lib/python2.7/dist-packages/zabbix_api.py", line 314, in method
    return self.universal("%s.%s" % (self.data["prefix"], name), opts[0])
  File "/usr/local/lib/python2.7/dist-packages/zabbix_api.py", line 71, in wrapper
    return self.do_request(self.json_obj(method, opts))['result']
  File "/usr/local/lib/python2.7/dist-packages/zabbix_api.py", line 321, in do_request
    return self.parent.do_request(req)
  File "/usr/local/lib/python2.7/dist-packages/zabbix_api.py", line 237, in do_request
    raise APITimeout("SSL read timeout",)
zabbix_api.APITimeout: SSL read timeout
```

**Comment by janssenlima** [comment]
Desativei a requisição de itens de discovery que estava com problemas.
Verifica se vai executar agora.

**Comment by tiago-cruz-movile** [comment]
Opa, agora foi tudo bem!! :+1: 

```
[+] - Selecione uma opção[0-6]: 1

Relatório de itens
==================

[INFO] Total de itens:  66551
[INFO] Itens habilitados:  61521
[INFO] Itens desabilitados:  4243
[ERRO] Itens não suportados:  787
```

**Comment by janssenlima** [comment]
Show de bola.
