### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '1w'

### ISSUE THREAD

**Issue by diegodrf** [janssenlima/ZabbixTuner#9]
Pelo o que entendi no código, ele está tentando converter o valor "1w" em inteiro.

164         if int(x["history"]) > 7:

[+] - Selecione uma opção[0-7]: 5
[+++] analisando itens não númericos
[+++] analisando itens ICMPPING com histórico acima de 7 dias
Traceback (most recent call last):
  File "./ZabbixTuner.py", line 486, in <module>
    main()
  File "./ZabbixTuner.py", line 484, in main
    menu()
  File "./ZabbixTuner.py", line 59, in menu
    menu_opcao()
  File "./ZabbixTuner.py", line 70, in menu_opcao
    diagnosticoAmbiente()
  File "./ZabbixTuner.py", line 164, in diagnosticoAmbiente
    if int(x["history"]) > 7:
ValueError: invalid literal for int() with base 10: '1w'

**Comment by janssenlima** [comment]
Fixed.
